# Builder Stage
FROM ghcr.io/snowdreamtech/rocky:10.2.0 AS builder

ENV QBT_PW_GEN_VERSION=1.0.2

RUN dnf update -y \
    && dnf install -y \
       golang \
       ca-certificates \
       wget \
       tar \
    && dnf clean all \
    && wget https://github.com/saltydk/qbt_pw_gen/archive/refs/tags/v${QBT_PW_GEN_VERSION}.tar.gz \
    && tar zxvf v${QBT_PW_GEN_VERSION}.tar.gz \
    && cd qbt_pw_gen-${QBT_PW_GEN_VERSION} \
    && go build -o passwd \
    && cp passwd ../

# Base Image (Rocky Variant)
FROM ghcr.io/snowdreamtech/rocky:10.2.0

# Build-time Configuration
ARG BUILDTIME \
    VERSION \
    REVISION \
    KEEPALIVE=1 \
    CAP_NET_BIND_SERVICE=0 \
    LANG=C.UTF-8 \
    UMASK=022 \
    DEBUG=false \
    PASSWORDLESS_SUDO=false \
    PGID=0 \
    PUID=0 \
    USER=root \
    WORKDIR=/root \
    QBITTORRENT_VERSION=5.2.1-1.el10_3

# Standard OCI Metadata
LABEL org.opencontainers.image.authors="Snowdream Tech" \
    org.opencontainers.image.title="qBittorrent Image Based On Rocky" \
    org.opencontainers.image.description="Docker Images for qBittorrent on Rocky. (amd64, arm64, ppc64le, s390x)" \
    org.opencontainers.image.documentation="https://hub.docker.com/r/snowdreamtech/qbittorrent" \
    org.opencontainers.image.base.name="snowdreamtech/rocky:10.2.0" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.source="https://github.com/snowdreamtech/qbittorrent" \
    org.opencontainers.image.vendor="Snowdream Tech" \
    org.opencontainers.image.created="${BUILDTIME}" \
    org.opencontainers.image.revision="${REVISION}" \
    org.opencontainers.image.url="https://github.com/snowdreamtech/qbittorrent"

# x-release-please-start-version
LABEL org.opencontainers.image.version="${VERSION:-4.6.3}"
# x-release-please-end

# Runtime Environment Configuration
ENV KEEPALIVE=${KEEPALIVE} \
    CAP_NET_BIND_SERVICE=${CAP_NET_BIND_SERVICE} \
    LANG=${LANG} \
    UMASK=${UMASK} \
    DEBUG=${DEBUG} \
    PASSWORDLESS_SUDO=${PASSWORDLESS_SUDO} \
    PGID=${PGID} \
    PUID=${PUID} \
    USER=${USER} \
    WORKDIR=${WORKDIR} \
    QBITTORRENT_VERSION=${QBITTORRENT_VERSION} \
    PEER_PORT=25413 \
    WEBUI_PORT=8080 \
    WEBUI_USER="" \
    WEBUI_PASS="" \
    WEBUI_LANG="en"

# Additional tooling and configuration
RUN dnf update -y \
    && dnf install -y --enablerepo=crb epel-release \
    && dnf install -y \
    qbittorrent-nox-1:${QBITTORRENT_VERSION} \
    vim \
    && dnf clean all \
    && mkdir -p /var/lib/qBittorrent/bin/ \
    && mkdir -p /var/lib/qBittorrent/cache/ \
    && mkdir -p /var/lib/qBittorrent/config/ \
    && mkdir -p /var/lib/qBittorrent/data/ \
    && mkdir -p /var/lib/qBittorrent/downloads/ \
    && mkdir -p /var/lib/qBittorrent/incomplete/ \
    && mkdir -p /var/lib/qBittorrent/logs/ \
    && mkdir -p /var/lib/qBittorrent/torrents/ \
    && rm -rfv /var/lib/qbittorrent

COPY --from=builder /root/passwd /var/lib/qBittorrent/bin/passwd

COPY config /var/lib/qBittorrent/config

# Container Orchestration Files
COPY entrypoint.d /usr/local/bin/entrypoint.d

RUN chmod +x /usr/local/bin/entrypoint.d/*

# Standard Healthcheck
HEALTHCHECK NONE

EXPOSE 8080 25413/tcp 25413/udp

# Process Execution
USER root
WORKDIR /root
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/bin/bash"]
