# Builder Stage
FROM ghcr.io/snowdreamtech/debian:13.5.0 AS builder

ENV QBT_PW_GEN_VERSION=1.0.2

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
       golang \
       ca-certificates \
       wget \
       tar \
    && wget https://github.com/saltydk/qbt_pw_gen/archive/refs/tags/v${QBT_PW_GEN_VERSION}.tar.gz \
    && tar zxvf v${QBT_PW_GEN_VERSION}.tar.gz \
    && cd qbt_pw_gen-${QBT_PW_GEN_VERSION} \
    && go build -o passwd \
    && cp passwd ../

# Base Image (Debian Variant)
FROM ghcr.io/snowdreamtech/debian:13.5.0

# Build-time Configuration
ARG BUILDTIME \
    VERSION \
    REVISION \
    KEEPALIVE=1 \
    CAP_NET_BIND_SERVICE=0 \
    LANG=C.UTF-8 \
    UMASK=022 \
    DEBUG=false \
    PASSWORDLESS_SUDO=false \
    PGID=0 \
    PUID=0 \
    USER=root \
    WORKDIR=/root \
    QBITTORRENT_VERSION=4.5.2-3+deb12u1 \
    FLOOD_VERSION=4.8.2

# Standard OCI Metadata
LABEL org.opencontainers.image.authors="Snowdream Tech" \
    org.opencontainers.image.title="qBittorrent (Flood) Image Based On Debian" \
    org.opencontainers.image.description="Docker Images for qBittorrent with Flood on Debian. (386, amd64, arm/v5, arm/v7, arm64, ppc64le, riscv64, s390x)" \
    org.opencontainers.image.documentation="https://hub.docker.com/r/snowdreamtech/qbittorrent" \
    org.opencontainers.image.base.name="snowdreamtech/debian:13.5.0" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.source="https://github.com/snowdreamtech/qbittorrent" \
    org.opencontainers.image.vendor="Snowdream Tech" \
    org.opencontainers.image.created="${BUILDTIME}" \
    org.opencontainers.image.revision="${REVISION}" \
    org.opencontainers.image.url="https://github.com/snowdreamtech/qbittorrent"

# x-release-please-start-version
LABEL org.opencontainers.image.version="${VERSION:-5.1.0}"
# x-release-please-end

# Runtime Environment Configuration
ENV KEEPALIVE=${KEEPALIVE} \
    CAP_NET_BIND_SERVICE=${CAP_NET_BIND_SERVICE} \
    LANG=${LANG} \
    UMASK=${UMASK} \
    DEBUG=${DEBUG} \
    PASSWORDLESS_SUDO=${PASSWORDLESS_SUDO} \
    PGID=${PGID} \
    PUID=${PUID} \
    USER=${USER} \
    WORKDIR=${WORKDIR} \
    QBITTORRENT_VERSION=${QBITTORRENT_VERSION} \
    PEER_PORT=25413 \
    WEBUI_PORT=8080 \
    WEBUI_USER="" \
    WEBUI_PASS="" \
    WEBUI_LANG="en" \
    FLOOD_AUTH=none \
    FLOOD_PORT=3000

# Additional tooling and configuration
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    qbittorrent-nox=${QBITTORRENT_VERSION} \
    nodejs \
    npm \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/lib/qBittorrent/bin/ \
    && mkdir -p /var/lib/qBittorrent/cache/ \
    && mkdir -p /var/lib/qBittorrent/config/ \
    && mkdir -p /var/lib/qBittorrent/data/ \
    && mkdir -p /var/lib/qBittorrent/downloads/ \
    && mkdir -p /var/lib/qBittorrent/incomplete/ \
    && mkdir -p /var/lib/qBittorrent/logs/ \
    && mkdir -p /var/lib/qBittorrent/torrents/ \
    && rm -rfv /var/lib/qbittorrent \
    && npm install --global flood

COPY --from=builder /root/passwd /var/lib/qBittorrent/bin/passwd

COPY config /var/lib/qBittorrent/config

# Container Orchestration Files
COPY entrypoint.d /usr/local/bin/entrypoint.d

RUN chmod +x /usr/local/bin/entrypoint.d/*

# Standard Healthcheck
HEALTHCHECK NONE

EXPOSE 3000 8080 25413/tcp 25413/udp

# Process Execution
USER root
WORKDIR /root
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/bin/bash"]
